### ISSUE TITLE
lstsq pinv vs inv

### ISSUE THREAD

**Issue by jaredbryan881** [tclements/Noise.jl#5]
https://github.com/tclements/Noise.jl/blob/ca996c929b7bbdcef03ca70a40701919a6193211/src/ArrayFuncs.jl#L20-L22

Should this be either ``coeff = pinv(A) * X`` or ``coeff = inv(A' * A) * A' * X``? This may affect detrending functions.

**Comment by tclements** [comment]
`pinv` is the pseudo-inverse, which inverts the SVD of the matrix. It's numerically more stable than the regular `inv`

**Comment by jaredbryan881** [comment]
Yes, the regression should be done with ``pinv``, but why are the coefficients of the best fit line not simply ``pinv(A) * X``? I am just making sure that this is not a typo since ``pinv(A) == inv(A' * A) * A'``. Are you one-to-one replacing ``inv()`` for ``pinv()``?

**Comment by tclements** [comment]
Yes, `pinv` is a replacement for `inv`. `inv(A' * A) * A' * X` is the least-squares solution.
