### ISSUE TITLE
MWCS: Sum sx2 over windows prior to element-wise division and summing over frequencies.

### ISSUE THREAD

**Issue by jaredbryan881** [tclements/Noise.jl#6]
When computing the errors, should ``sx2`` first be summed over all time windows at each frequency (yielding an array the same length as the frequency array)? Then, instead of dividing ``s2x2`` by a scalar, it is element-wise division of two arrays: the window-summed ``sx2`` and the current window's ``s2x2``. 
It would turn

https://github.com/tclements/Noise.jl/blob/c64f6973ccbc2e84cbaa302bf897062fb38eaec2/src/VelocityChange/MWCS.jl#L152-L165

into 

```
# Calculate the slope with a weighted least square linear regression
# forced through the origin
# Pre-sum sx2 over N windows
sx2 = zeros(length(v))
for ii=1:N sx2 .+= sum(w[:,ii] .* v.^2) end
for ii = 1:N
    model = glm(@formula(Y ~0 + X),DataFrame(X=v,Y=phi[:,ii]),Normal(),
                IdentityLink(),wts=w[:,ii])
    # a much faster, unweighted version of this is: m = v \ phi
    dt[ii] = coef(model)[1]

    # Errors
    # σ^2_ϕ
    e = sum((phi[:,ii] .- dt[ii] .* v).^2) / (length(v) - 1)

    s2x2 = (v .* w[:,ii]).^2
    err[ii] = sqrt(e * sum(s2x2 ./ sx2.^2))
end
```

**Comment by tclements** [comment]
I don't think so, because pre-summing this way would include weights from other windows. The error measurement for each window should only have weights (cross-coherence) for that window.

**Comment by tclements** [comment]
Here's an excerpt from the original python code https://github.com/ROBelgium/MSNoise/blob/master/msnoise/move2obspy.py 
```
e = np.sum((phi - m * v) ** 2) / (np.size(v) - 1)
s2x2 = np.sum(v ** 2 * w ** 2)
sx2 = np.sum(w * v ** 2)
e = np.sqrt(e * s2x2 / sx2 ** 2)
```

**Comment by jaredbryan881** [comment]
Yes, that is a good point. Pre-summing could allow dissimilar sections of the signals to down-weight the coherent sections. Thanks for the reference and clarification. Closing issue.
